name: Publish dev

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: 'Use NodeJS 16' # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '16.18.1'

      - name: Build dependencies
        run: |
          node bootstrapEnv
          npx lerna bootstrap
          yarn build

      - name: 'Setup npm'
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Version and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          npx lerna version --conventional-commits --conventional-prerelease --preid beta --force-git-tag --yes
          npx lerna publish from-git --force-git-tag --dist-tag next --yes --summary-file

      - name: 'Broadcast published versions on Slack'
        run: node etc/slack --api=$SLACK_API --commit-message=$GIT_LATEST_COMMIT_MESSAGE
        env:
          SLACK_API: ${{ secrets.SLACK_API }}
          GIT_LATEST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
